### ISSUE TITLE
Finish polishing metadata validation patch

### ISSUE THREAD

**Issue by rosarior** [mayan-edms/mayan-edms#104]

**Comment by notenbrood** [comment]
Would this also include metadata data types, or just support for metadata validation functions?

Also, would this include a parsing function for metadata? It's one thing to accept multiple date formats, it's another to store them in the same way.

I'd be willing to help code a resolution to this issue as it would be critical in our adoption of Mayan as our choice of EDMS

**Comment by rosarior** [comment]
Thanks for offering to help! A patch submitted by @gwalborn implemented (9cd37537461347f79ff0429e4b8b16fd2446798d) both validation scenarios: validation and parsing, which also solves discrimination of input data type. His commit has the complete explanation. That is ticket is meant to get the functionality ready for release and document it.

**Comment by rosarior** [comment]
Other pertinent changes: 9380157406dc13393b8b1e95f2e4278ef339681b 490e9a1e4239faeb2261928a27f958e6b458a8b0 e4d68cb7111e06614ddb21cda0ff1e0d48817d3d f5e1adedfa0d4b0e0fa7e9139b1906468016b97d
