### ISSUE TITLE
Merge locale profile into user details

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#135]
If there aren't any implications permissionwise, the new locale profile could be merged into the user details.

**Comment by rosarior** [comment]
Thought about it too but the migration required renaming db tables to avoid losing ACLs and group memberships, so implemented it as a separate profile model with a One to one field to the User model. Overriding the User model is best done when a custom authentication is required, for the two extra fields that were added to the account it was a bit overkill.

I'm in favor though of replacing hardcoded User model imports for settings.AUTH_USER_MODEL and get_user_model usage as was the purpose of issue #96 to pave the way in case we go with a custom User model in the future.

**Comment by rosarior** [comment]
Closing for now until the user profile gets more complex and requires a custom model.
