### ISSUE TITLE
Missing cleanup of temporary files

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#136]
In my current test setup after processing of new documents files are leftover namely from the office converter and unpaper(?). If /tmp is on a tmpfs this can lead quite fast to memory exhaustion, when processing some big documents.

**Comment by mbehrle** [comment]
Biggest leftover files are gs files from document preview, when viewing detailed pages.

**Comment by rosarior** [comment]
I agree to do automatic removal, but currently I think the converter app does caching of office and text documents to reduce the calls to Libre Office. Moving this for version 2.0 because a careful code review will be needed.

**Comment by rosarior** [comment]
The converter subsystem has been rebuilt from scratch, it uses Python file like objects and in-memory PIL Image instances to move image data from one method to another. Temporary file leftover is now minimal.
