### ISSUE TITLE
Enhancement of language selection

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#137]
When having to chose from a language, the selection field presents a big selection, that also contains languages you probably will never need depending on your environment. It would be good, if it would be possible to present only a subset of all languages.

**Comment by mbehrle** [comment]
This is meant for the language selector on the upload form.

**Comment by rosarior** [comment]
From the patch commit message:

To override the default list of 600+ languages add a configuration entry to your settings/local.py like so:
DOCUMENTS_LANGUAGE_CHOICES = [('eng', 'English'), ('deu', 'German')]

to make the list translatable import ugettext_lazy and enclose the language name with _():

from django.utils.translation import ugettext_lazy as _
DOCUMENTS_LANGUAGE_CHOICES = [('eng', _('English')), ('deu', _('German'))]

**Comment by mbehrle** [comment]
Tested, works like a charm!
