### ISSUE TITLE
Possibility to keep zoom factor

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#138]
With the new amazing GUI we have the quick view of a document with the scroll down region in the Document Preview. To read a document page by page we now can use the Details Page. The reader may want to use a certain zoom factor to read through the doument, e.g. to have displayed the whole page at once. But when toggling to the next page he will lose the zoom factor from the last page. It would be nice, if the reader could keep the last used zoom factor.

**Comment by rosarior** [comment]
I liked this idea very much, thanks! Please test.

**Comment by mbehrle** [comment]
Tested, works smoothly and is a big facilitation!
