### ISSUE TITLE
Simplify permission hierarchy (only roles will have permissions)

### ISSUE THREAD

**Issue by rosarior** [mayan-edms/mayan-edms#142]
Instead of allowing roles, groups and users to have a global permission and/or a per object permissions attached to them, only roles will have global permissions and per object permissions. This will leave roles as an unit of permission and groups will be instead a unit of organization. Users and groups will still be able to be a part of a Role, inheriting it's permissions this way. This change will greatly simplify the verification of permissions on each view, the filtering of results on a per permission basis, speeding things up and lower the chances of permissions related bugs.

This change will also allow the removal of the generic foreign key (ContentType and object_id) link between permissions, ACLs, roles, groups and users. The relationship will become a ForeignKey to the Role model only, meaning half the DB queries with just that change.

**Comment by yitjob** [comment]
This would restrict the View Documents permission to documents uploaded by users of the same group only? Let's say we have a role named Uploaders and then the groups "Finance" and "Sales". With this enhancement will the members of Finance see only document uploaded by Finance members only?

**Comment by rosarior** [comment]
No, this change removed the ability to assign permissions to individual users and groups. Users and group should be organizational units and not authorization units. Roles will be the only authorization unit being able to receive perssions either globally or per document.

This change simplifies permission granting internal code. 

Same group permission granting is not possible now as a user might belong to more than one group and/or role. Which role/group permissions should be applied to the new document? All? Merge? Exclusion? 

I'm not saying is not a good idea (it's a great idea) vu

**Comment by yitjob** [comment]
Well, it's fine anyway, but... It is only necessary to have an account with View Documents enabled, to see everything on the server, or am I missing something?

If different roles could be restricted to certain documents, or folders, or something else, not being able to browse the whole document repository, it would make more sense I think. In case you don't mind I'd like to see if I can propose some aproach in this topic.

Perhaps a special user "Same-role-user" may allow a single set of permissions whilst enabling team colaboration on the documents uploaded?

**Comment by rosarior** [comment]
> Well, it's fine anyway, but... It is only necessary to have an account with View Documents enabled, to  see everything on the server, or am I missing something?

Yes, at the moment giving "View Documents" globally to a role, group or user will allow viewing all documents. You can also grant "View Documents" permission per specific documents to an user, group or role, **manually**, this is called an Access Control List (ACL). There is no method to give an user permissions over certain documents based on the group/role of the user that uploaded the document automatically at upload time. The closest I've been able to implement something like that, that works for all cases, is enabling Default Access Control Lists per document type. Global permissions link two objects: holder (User, Group, Role) and permissions. ACLs like three objects: holder, permissions, and individual object instances (Document, Folder, Tag).

> If different roles could be restricted to certain documents, or folders, or something else, not being > able to browse the whole document repository, it would make more sense I think. 

That is possible at the moment, but you have to set the restrictions by hand. There is no automatic way that works in all settings. 

> In case you don't mind I'd like to see if I can propose some approach in this topic.

Sure thing! :)

> Perhaps a special user "Same-role-user" may allow a single set of permissions whilst enabling
> team collaboration on the documents uploaded?

There are two special users right now: *Creator* and *Anonymous*, *Creator* acts as variables during document creation, and *Anonymous* represents any user not logged in. Something like *Same-role-user* could be plugged in that code, the only thing missing is role selection when an user belongs to more than one role.

**Comment by rosarior** [comment]
Added support for permission inheritance by parent object (bc3eed143cc12ff09dbdcd286ab38ef074b79753), this means that access controls can be granted to a role for a document type and said role will inherit that access to all documents of that type.

ie: Grant 'document view' permission to 'Finance' role for 'Financial statement' document type. Members of the 'Finance' role will be able to view any document of the type 'Financial statement' even if they are not granted that permission for each document, because their role was granted that permission to the document type itself.

![screenshot from 2015-07-10 03 03 29](https://cloud.githubusercontent.com/assets/413955/8613758/7adb7bf2-26b0-11e5-88ed-4b960833987d.png)


![screenshot from 2015-07-10 03 04 19](https://cloud.githubusercontent.com/assets/413955/8613761/7f9841b6-26b0-11e5-9ba7-189e7e5c935a.png)

**Comment by yitjob** [comment]
@rosarior the special users don't exist anymore y v2.0.0rc1?
