### ISSUE TITLE
Behavior of 'Edit metadata' (Recent Documents)

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#144]
When trying to edit metadata from the the Recent Documents page, it  just allows to save without being possible to edit something.

**Comment by mbehrle** [comment]
This has turned out to be a misunderstanding on my side: when trying to edit metadata on a document without any metadata, the only option is to save (without having obviously changed anything).
So in the case of missing metadata it would be better to either show a message, that there is nothing to edit or to provide the form to add metadata directly.

**Comment by rosarior** [comment]
Empty document metadata detection only worked when a single document was selected and manually navigated to the metadata tab. Made if generic now and works for one directly selected, one selected from a document list or multiple selected documents from a document list.

**Comment by rosarior** [comment]
The generic detection of empty metadata was also extended to the document metadata remove views which exhibited the same previous behavior.

**Comment by mbehrle** [comment]
Cool. Works.
