### ISSUE TITLE
Periodic task not initiated for mail boxes and watch folders

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#146]
The periodic task scheduler seems to be not initiated for mail boxes and watch folders, but will have to recheck that.

**Comment by rosarior** [comment]
I forgot to mention that a Celery Beat periodic scheduler must be launched. 

Previously Mayan had it's own periodic scheduler, with the move to Celery, Celery Beat must be used together with the workers. It must be launched with:

    celery -A mayan beat -l INFO

Only one Celery Beat scheduler can be running at a time. You can tell one of the workers to run as a periodic scheduler too by adding -B to the command line, for example:

    celery -A mayan worker -l DEBUG -Q checkouts,mailing,uploads,converter,ocr,tools,indexing,metadata -Ofair -B

To check on the periodic tasks go to the admin at http://127.0.0.1:8000/admin/djcelery/periodictask/ there should a periodic task for each background document source (emails, watch folders), with the name check_interval_source-{{ PK }}: every {{ # }} seconds. Example: check_interval_source-5: every 30 seconds.

For simplicity I use the -B option every time and only use a separate celery -A mayan beat process when I want to examine the periodic scheduler output for errors.

**Comment by mbehrle** [comment]
Thx for the explanation, will have to dig deeper into the celery docs to get more familiar with this amazing stuff. Works smoothly!
