### ISSUE TITLE
New document via watch folder doesn't update index

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#147]
When new documents are imported from watch folders, the indices aren't updated. Manually updating the index shows them.

**Comment by rosarior** [comment]
Documents imported from watch folders or email do not contain metadata values, that is why they are not being indexed. To make it easier to find the documents with required metadata still not entered there is a new tool button called "Missing metadata". Is a step towards your idea of a post OCR/upload processing queue.

**Comment by mbehrle** [comment]
As it is possible to have metadata independent indices (like document.date_added) it would be helpful to run the index creation always. E.g. it is possible with such an index to have a look at documents imported at a special date, which could also be a method to look for documents not yet classified.

Should we perhaps rename the tool button "Missing metadata" to ""Missing required metadata" ? Best of course would be to be able search for all types (required or optional) of metadata.

**Comment by rosarior** [comment]
Indexes are now recalculated on new document uploads too.
REF: 8cc05bbefb6f101f45d65817ecd0725a0b9bc244
Location: https://github.com/mayan-edms/mayan-edms/blob/development/mayan/apps/document_indexing/apps.py#L49

Makes use of the new **post_document_created** signal.
