### ISSUE TITLE
Get rid of eval

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#151]
At several places, e.g. the dynamic title of smart links, it is possible to get python code evaluated directly. So it is possible to put in there strings like
__import__('os').listdir(__import__('os').getcwd())
and of course much more evil things.
While this is more or less restricted to administrative users, it is nevertheless a broad possibility to break into the system.

We should evaluate the possibility to use literal_eval or provide a completely different solution.

**Comment by rosarior** [comment]
Yes, my choice would be either regular expressions or user-supplied functions like the ones now used for metadata validation.

**Comment by rosarior** [comment]
Saltstack uses a combination of YAML + Jinja. Also features selectable interpreters.

**Comment by rosarior** [comment]
Some areas have been changed to use YAML only for data structures. For index, metadata and smart links expressions  Dango's templating language + YAML will be used. Better without writing and entire scripting language from scratch.
