### ISSUE TITLE
Document content empty

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#152]
With current trunk the tab 'Document content ' is empty after succesfull ocr of the document.

**Comment by rosarior** [comment]
The problem seems to be this line: https://github.com/mayan-edms/mayan-edms/blob/development/mayan/apps/ocr/parsers/__init__.py#L167

When the parsing fails the OCR kicks in, empty parsing is not being detected. The test works on SQLite but fails on MySQL and Postgres. DB Unicode issue?

Started failing after the addition of from \__future__ import unicode_literals for Python3 compatibility.

**Comment by rosarior** [comment]
There has to be a better way to detect failed parsing from Slate that comparing text stored to '/x0c'.

**Comment by rosarior** [comment]
I see the search and OCR tests fail on Travis CI but can't replicate even on the Vagrant box using MySQL. Any additional finding?

**Comment by mbehrle** [comment]
That's what I can get fom the worker:
```
^[[2015-01-28 02:31:38,858: INFO/MainProcess] Received task: sources.tasks.task_source_upload_document[29ae9523-0f7e-4185-8ee2-7e91c68fb938]
documents.models <32577> [DEBUG] "new_version() creating new document version"
[1;34m[2015-01-28 02:31:39,020: DEBUG/Worker-2] creating new document version[0m
[1;33m[2015-01-28 02:31:39,040: WARNING/Worker-2] Traceback (most recent call last):[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] msg = self.format(record)[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] File "/usr/lib/python2.7/logging/__init__.py", line 732, in format[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] return fmt.format(record)[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] File "/usr/lib/python2.7/logging/__init__.py", line 471, in format[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] record.message = record.getMessage()[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] msg = msg % self.args[0m
[1;33m[2015-01-28 02:31:39,041: WARNING/Worker-2] TypeError: coercing to Unicode: need string or buffer, NoneType found[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] Logged from file api.py, line 104[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] Traceback (most recent call last):[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] msg = self.format(record)[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] File "/usr/lib/python2.7/logging/__init__.py", line 732, in format[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] return fmt.format(record)[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/celery/utils/log.py", line 138, in format[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] msg = logging.Formatter.format(self, record)[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] File "/usr/lib/python2.7/logging/__init__.py", line 471, in format[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] record.message = record.getMessage()[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] msg = msg % self.args[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] TypeError: coercing to Unicode: need string or buffer, NoneType found[0m
[1;33m[2015-01-28 02:31:39,042: WARNING/Worker-2] Logged from file api.py, line 104[0m
converter.office_converter <32577> [DEBUG] "convert() command: [u'/usr/bin/libreoffice', u'--headless', u'--convert-to', u'pdf', '/tmp/tmpyYQgr5', u'--outdir', u'/tmp']"
[1;34m[2015-01-28 02:31:39,043: DEBUG/Worker-2] command: [u'/usr/bin/libreoffice', u'--headless', u'--convert-to', u'pdf', '/tmp/tmpyYQgr5', u'--outdir', u'/tmp'][0m
converter.office_converter <32577> [DEBUG] "convert() return_code: 0"
[1;34m[2015-01-28 02:31:39,603: DEBUG/Worker-2] return_code: 0[0m
converter.office_converter <32577> [DEBUG] "convert() stderr: "
[1;34m[2015-01-28 02:31:39,604: DEBUG/Worker-2] stderr: [0m
converter.office_converter <32577> [DEBUG] "convert() filename: tmpyYQgr5"
[1;34m[2015-01-28 02:31:39,604: DEBUG/Worker-2] filename: tmpyYQgr5[0m
converter.office_converter <32577> [DEBUG] "convert() extension: "
[1;34m[2015-01-28 02:31:39,604: DEBUG/Worker-2] extension: [0m
converter.office_converter <32577> [DEBUG] "convert() converted_output: /tmp/tmpyYQgr5.pdf"
[1;34m[2015-01-28 02:31:39,604: DEBUG/Worker-2] converted_output: /tmp/tmpyYQgr5.pdf[0m
converter.api <32577> [DEBUG] "get_page_count() office_converter.exists: True"
[1;34m[2015-01-28 02:31:39,604: DEBUG/Worker-2] office_converter.exists: True[0m
ocr <32577> [DEBUG] "post_version_upload_ocr() received post_version_upload"
[1;34m[2015-01-28 02:31:41,425: DEBUG/Worker-2] received post_version_upload[0m
ocr <32577> [DEBUG] "post_version_upload_ocr() instance pk: 85"
[1;34m[2015-01-28 02:31:41,425: DEBUG/Worker-2] instance pk: 85[0m
documents.models <32577> [DEBUG] "new_version() new_version saved"
[1;34m[2015-01-28 02:31:41,436: DEBUG/Worker-2] new_version saved[0m
[2015-01-28 02:31:41,496: INFO/MainProcess] Task sources.tasks.task_source_upload_document[29ae9523-0f7e-4185-8ee2-7e91c68fb938] succeeded in 2.63696414605s: None
```

**Comment by rosarior** [comment]
This look suspicious:

TypeError: coercing to Unicode: need string or buffer, NoneType found
WARNING/Worker-2] Logged from file api.py, line 104

It is this line: https://github.com/mayan-edms/mayan-edms/blob/development/mayan/apps/converter/api.py#L104

It is saying that there is no office converter backend initialized at the moment the document was being introspected to determine the page count, however it converted successfully then to PDF (converted_output: /tmp/tmpyYQgr5.pdf").

Does the problem occurs for all document types or only for office documents?
Remove the line 104 (logger.debug) of converter/api.py to see if the TypeError is what's causing the task to end abruptly.

**Comment by rosarior** [comment]
Test are running correctly after commit adf47b9399f5123a9209d6343270eca0546684dc
Travis: https://travis-ci.org/mayan-edms/mayan-edms/builds/48727090

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] Document content empty (#152)" (Wed, 28
  Jan 2015 12:59:10 -0800):

> This look suspicious:
> 
> TypeError: coercing to Unicode: need string or buffer, NoneType found
> WARNING/Worker-2] Logged from file api.py, line 104
> 
> It is this line:
> https://github.com/mayan-edms/mayan-edms/blob/development/mayan/apps/converter/api.py#L104
> 
> It is saying that there is no office converter backend initialized at the
> moment the document was being introspected to determine the page count,
> however it converted successfully then to PDF
> (converted_output: /tmp/tmpyYQgr5.pdf").
> 
> Does the problem occurs for all document types or only for office documents?
> Remove the line 104 (logger.debug) of converter/api.py to see if the
> TypeError is what's causing the task to end abruptly.

Thx for the fixes and better debugging messages. I just tested for a number of
document types and it now seems to work smoothly (I detected btw another
document with fake mimetype: an ods was recognized as archive/java, but after
opening and resaving with libreoffice it processed correctly).

I had some errors, but that should be related the missing migration of the tag
app in this database. Will now test the migration and do a final test of this
issue with a correct database.


-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by rosarior** [comment]
Yeah, on the mimetype detection we are at the mercy of libmagic, not much to do there and file extensions are not to be trusted. Which is the default behavior of Python's builtin mimetypes library and the reason python-magic was used instead. 

Document content resolved, so I'm going to close this issue and continue working on the two failing migrations.
