### ISSUE TITLE
south migration with postgres: documents: 031_remove_orphan_documents

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#153]
Still some migration issues with postgres when running on a production DB, splitting issues for better readability.

When running 031_remove_orphan_documents, there are some stale content types (sources)
(see also https://github.com/mbehrle/mayan-edms/tree/feature/migration).

When confirming the deletion of the content types:

Relation "actstream_follow" doesn't exist at char 13
DELETE FROM "actstream_follow" WHERE "actstream_follow"."content_type_id" IN (55)

Running migration a second time doesn't fail (skips the step?).

**Comment by rosarior** [comment]
Deletion of stale content types should never cause an error so there must be something somewhere else. Maybe an out of order migration? I will try to recreate this.

**Comment by mbehrle** [comment]
Tried to get the tables of act_stream with
 
    depends_on = (
        ('act_stream', '0001_initial'),
    )

 or

    depends_on = (
        ('act_stream', '0007_auto__add_field_follow_started'),
    )

but result is

south.exceptions.DependsOnUnmigratedApplication: Migration 'documents:0030_auto__add_unique_documenttypefilename_document_type_filename' depends on unmigrated application 'act_stream'.

So this is not the real clue.

**Comment by rosarior** [comment]
Try with 'actstream' without the underscore, it is the app name as it was packaged.

**Comment by mbehrle** [comment]
Thx. So this one is solved. Ref https://github.com/mayan-edms/mayan-edms/pull/156
