### ISSUE TITLE
Header does not fit list on documents/list on small screens (laptop)

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#155]
screenshot attached
![bildschirmfoto - 28 01 2015 - 02 10 49](https://cloud.githubusercontent.com/assets/304732/5930698/6cf4e804-a693-11e4-9f3b-b3f5f567ea4e.png)

**Comment by rosarior** [comment]
I will try to tweak the CSS but this template is old, in XHTML 1.0, not responsive, etc, I'm not too hopeful.

**Comment by mbehrle** [comment]
Will hopefully be solved with https://github.com/mayan-edms/mayan-edms/pull/121 in 2.0

**Comment by rosarior** [comment]
You are correct. The new template uses responsive tables (http://getbootstrap.com/css/#tables-responsive) which collapse into a viewport with scrollbars on small screen. I think we can close this one.

![screenshot from 2015-04-01 02 12 11](https://cloud.githubusercontent.com/assets/413955/6935519/91171164-d814-11e4-9835-bfdf7b124935.png)
