### ISSUE TITLE
Plural form not matching singular form in ocr app

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#158]
The issue is about those strings with differing arguments for singular and plural:

#: views.py:119
#, python-format
msgid "Are you sure you wish to delete the entry: %(entry)s?"
msgid_plural "Are you sure you wish to delete these %(count)d entries."
msgstr[0] ""
msgstr[1] ""

which results in

Pushing translations for resource mayan-edms.apps-ocr:
Pushing 'de_DE' translations (file: mayan/apps/ocr/locale/de_DE/LC_MESSAGES/django.po)
Error uploading file: There is a syntax error in your file.
Line 169: a format specification for argument 'entry', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
Line 186: a format specification for argument 'entry', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
msgfmt: found 2 fatal errors

Obviously the format expects the arguments of being the same in singular as in plural.

How shall we proceed for this release? For the sake of completeness I pushed the ocr translation with empty msgstr to transifex. Probably the best solution is to recommend this for all translators?

**Comment by rosarior** [comment]
I thought they were all fixed, my opinion is to fix those before release. Aside from the OCR app messages, found any app with the same error?

**Comment by rosarior** [comment]
Just checked and the issue was still open :/ https://github.com/mayan-edms/mayan-edms/issues/64 Guess there is still work to do on that one.

**Comment by mbehrle** [comment]
Ok. The ocr app is the only place to my knowledge with two different strings.

**Comment by mbehrle** [comment]
Fixed with https://github.com/mayan-edms/mayan-edms/commit/9c2412f4878adf2b94e97a930cecf82961fc70e8
