### ISSUE TITLE
Edit existing document's metadata

### ISSUE THREAD

**Issue by miek770** [mayan-edms/mayan-edms#165]
I get the following error when trying to edit a document's metadata, when it cleary has metadata:

![error](https://cloud.githubusercontent.com/assets/3951483/6212610/79c90912-b5b5-11e4-8978-948194e0e752.png)

I've very recently installed mayan 1.1 via PIP, using a 1.0 postgreSQL database migrated per the instructions in the wiki (several "mayan-edms.py migrate stuff 0001 --fake (then not fake) --settings=mayan.settings.my_settings").

Note that I had a nightly database backup so if things end up being broken I can always go back and reinstall 1.0, but I believe the metadata got slightly corrupted through the migration (there is another metadata error I'll report unless you think migration errors aren't relevant). I'd like to find a way to repair the database if possible.

Thanks.

**Comment by mbehrle** [comment]
* Michel: " [mayan-edms] Edit existing document's metadata (#165)" (Mon, 16 Feb
  2015 05:32:19 -0800):

> I get the following error when trying to edit a document's metadata, when it
> cleary has metadata:
> 
> ![error](https://cloud.githubusercontent.com/assets/3951483/6212610/79c90912-b5b5-11e4-8978-948194e0e752.png)
> 
> I've very recently installed mayan 1.1 via PIP, using a 1.0 postgreSQL
> database migrated per the instructions in the wiki (several "mayan-edms.py
> migrate stuff 0001 --fake (then not fake)
> --settings=mayan.settings.my_settings").

You probably meant the release notes, not the wiki?
 
> Note that I had a nightly database backup so if things end up being broken I
> can always go back and reinstall 1.0, but I believe the metadata got slightly
> corrupted through the migration (there is another metadata error I'll report
> unless you think migration errors aren't relevant). I'd like to find a way to
> repair the database if possible.

Please post the output of the migration run, otherwise it is difficult to help.

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by miek770** [comment]
Yes sorry I meant the release notes.

I didn't keep the migration run output but will try to recreate it using my backups. While trying to rename my database from mayan to mayan-1.1 I noticed a filesystem corruption in /var/lib/postgres/data/base. It probably isn't related to my metadata problem but I'll run some additional checks and report back.

If I can reproduce the error I'll post my migration run output.

**Comment by miek770** [comment]
Apologies, I redid the whole migration (with no error) after fixing my filesystem and couldn't reproduce the error I got at first. Closing the issue.

**Comment by mbehrle** [comment]
* Michel: " Re: [mayan-edms] Edit existing document's metadata (#165)" (Tue, 17
  Feb 2015 12:39:03 -0800):

> Apologies, I redid the whole migration (with no error) after fixing my
> filesystem and couldn't reproduce the error I got at first. Closing the issue.

Thanks for checking!


-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6
