### ISSUE TITLE
Missing explanation for making site available outsite of localhost

### ISSUE THREAD

**Issue by braegel** [mayan-edms/mayan-edms#166]
I suppose this is a problem of binding to 127.0.0.1. I don't find a hint in the installation guide, in the FAQ nor in the github readme. I think i need to change the binding to 0.0.0.0. Maybe it is even an other problem. However this needs to be documented in the installation guide.

**Comment by mbehrle** [comment]
* Bernd Brägelmann: " [mayan-edms] Missing explanation for making site
  available outsite of localhost (#166)" (Tue, 17 Feb 2015 10:51:52 -0800):

> I suppose this is a problem of binding to 127.0.0.1. I don't find a hint in
> the installation guide, in the FAQ nor in the github readme. I think i need
> to change the binding to 0.0.0.0. Maybe it is even an other problem. However
> this must be documented in the installation guide.

That's a configuration option for django apps in general, not especially Mayan.
You find it e.g. here

https://docs.djangoproject.com/en/1.7/ref/django-admin/

or more exactly here

https://docs.djangoproject.com/en/1.6/ref/django-admin/#runserver-port-or-address-port

If you find that this should be included in the documentation, please make a
Pull Request with the changes you have in mind.

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by rosarior** [comment]
I'm hesitant to add such information to the documentation because it could give the impression that executing runserver while binding to 0.0.0.0 is a viable way to use Mayan EDMS.

**Comment by rosarior** [comment]
Closing for now, if you would like to provide a section with an adequate explanation when and how runserver with 0.0.0.0 could be used, feel free to re-open and/or send a pull request. Thanks!
