### ISSUE TITLE
Add document indexing filesystem mirroring

### ISSUE THREAD

**Issue by rosarior** [mayan-edms/mayan-edms#173]
This feature was removed before the release of version 1.1 due to the big changes caused by the use of celery. The document indexing code is stable enough for this feature to be added again.

**Comment by rosarior** [comment]
Looking to reimplement this feature as a Django FUSE filesystem, instead of just doing symbolic links, would allow to expose indexes even when the storage backend is not the local filesystem.

**Comment by mbehrle** [comment]
> Looking to reimplement this feature as a Django FUSE filesystem, instead of
> just doing symbolic links, would allow to expose indexes even when the
> storage backend is not the local filesystem.

+1!


-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6
