### ISSUE TITLE
JSON API 500 error

### ISSUE THREAD

**Issue by pycal** [mayan-edms/mayan-edms#191]
I've added a few documents, document types, and metadata, and am receiving the following 500 error when querying the REST API at /api/v0/documents/documents/

`Could not resolve URL for hyperlinked relationship using view name "documenttype-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.`

**Comment by pycal** [comment]
Looks like this is just related to the version of mayan used in the docker image; the REST API and new endpoints work on my local install.

**Comment by rosarior** [comment]
Yes, the version in the docker image is a release candidate, will update to 1.1.0. Started that repo but there doesn't seems much interest for Mayan EDMS in Docker.

**Comment by rosarior** [comment]
Closing for now, please re-open if new API errors are found, thanks!
