### ISSUE TITLE
Error during template rendering on /document/folder/add with non-admin user

### ISSUE THREAD

**Issue by mnard** [mayan-edms/mayan-edms#199]
Hello,
I've a non-admin user with a role that allows "add document to folder". 
When trying to perform this operation with this user, I get:

AttributeError at /folders/document/multiple/folder/add/
'list' object has no attribute 'all'
...
Error during template rendering
In template /home/max/.virtualenvs/kt-mayan/src/mayan/mayan/apps/main/templates/main/generic_form_instance.html, error at line 52

The same operation with admin user succedes: so I suppose is something related to permissions.

**Comment by rosarior** [comment]
I was unable to trigger this issue. There is a line to catch this AttributeError exception and reprocess the access control check in a different way: https://github.com/mayan-edms/mayan-edms/blob/master/mayan/apps/acls/managers.py#L247

Does it happen all the time or with a specific steps/sequence? What version are you using?

Check the console it should say the the exact line the error is happening and please copy and paste it here.

**Comment by mnard** [comment]
Version used: 1.1.0
I'm very sorry: I cannot reproduce the effect any longer. I suspect that's because I kept tweaking permissions without knowing I was touching part of the problem cause.
I'll notify you if I'll reproduce it again.
