### ISSUE TITLE
Remove multiple document download support

### ISSUE THREAD

**Issue by rosarior** [mayan-edms/mayan-edms#205]
The ZIP file is generated in the same process as the request, blocking the request. Would need to convert to a background task but there is no way to alert user when the ZIP is ready for download. Emailing a link would be another options but we need to keep the ZIP file for sometime and auto remove, having to create another schedule job for clean-up. Custom web app GUIs are experiencing problems too with this. Problems outweigh benefits.

**Comment by luzfcb** [comment]
http://policystat.github.io/jobtastic/ ? 
ps.: I never used"

**Comment by pycal** [comment]
This is actually a critical feature for my users, and it seems to be working acceptably; are you noticing some performance problem?

**Comment by rosarior** [comment]
@luzfcb Never heard of jobtastic, looks very interesting, thanks!
@pycal The feature is causing HTTP timeouts in some deployments and redirection issues on custom UIs. If jobtastic work wells, this can be reworked a bit and keep the feature. Thanks for the feedback!
