### ISSUE TITLE
Ability to add subfolders

### ISSUE THREAD

**Issue by hmrc87** [mayan-edms/mayan-edms#210]
Hi, I've read that that you talked about this feature on Djangocon last year

http://mayan-edms.narkive.com/Yy4VbvPv/mayan-edms-745-is-there-a-way-for-creating-subfolders

Is this still on the roadmap?

**Comment by rosarior** [comment]
It's been discussed a lot, the main problem is the permission setup, will it be only for the top level folder or for each level of the structure. https://github.com/mayan-edms/mayan-edms/issues/31
