### ISSUE TITLE
tesseract fails with german language (wrong abbreviation)

### ISSUE THREAD

**Issue by toha** [mayan-edms/mayan-edms#211]
If I select "German" as language while uploading a new document, the shourtcut "ger" is send by the browser to the backend and will be used while executing the tesseract shell command. However tesseract expects the shortcut "deu" for German content, so it fails with the wrong shortcut. 
example output:

```
$ tesseract pangram.jpg stdout -l ger
Error opening data file /usr/share/tesseract-ocr/tessdata/ger.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'ger'
Tesseract couldn't load any languages!
Could not initialize tesseract.

$ tesseract pangram.jpg stdout -l deu
Fix Schwyz! quäktjürgen blöd vom Paß.
```

**Comment by startmat** [comment]
Hi, it looks like that tesseract is using the "terminology" language abbreviation of pycountry.language module.
mayan is using and storing (in database) the bibliographic
see module apps/documents/settings.py
LANGUAGE_CHOICES = [(i.bibliographic, _(i.name)) for i in list(pycountry.languages)]

There are only a few languages where there is a diff between "bibliographic" and "terminology" abbreviations. 
See: 
https://www.loc.gov/standards/iso639-2/php/code_list.php
and see gist to check in pycountry:
https://gist.github.com/startmat/da1bb6dcedc9e30dd661

As an quick solution I added an line to apps/ocr/backends/tesseract.py:
```python
        if language is not None:
            lang = pycountry.languages.get(bibliographic=language)
            command.extend(['-l', lang.terminology])
```
May be in future the decision to store the  "terminology" value instead "bibliographic" value is taken. But this means that there is the need of an migration script.

Matthias

**Comment by rosarior** [comment]
Thanks for figuring all this out @startmat! This info will help to code a patch or a permanent move to "terminology" for internal language codes.
