### ISSUE TITLE
Replace default email domain

### ISSUE THREAD

**Issue by ANAT01** [mayan-edms/mayan-edms#216]
In [code](https://github.com/mayan-edms/mayan-edms/blob/774a0189120b8993c0b7099f900116c231193958/mayan/apps/common/__init__.py#L62) used [exist domain](http://autoadmin.com) for admin email by default.

It may be not secure.

Change autoadmin@autoadmin.com to autoadmin@[example.com](https://en.wikipedia.org/wiki/Example.com)

**Comment by thequbit** [comment]
:+1: Great find.

**Comment by rosarior** [comment]
Good find, thanks!
