### ISSUE TITLE
Odoo Integration

### ISSUE THREAD

**Issue by tebanep** [mayan-edms/mayan-edms#234]
Which do you think would be the best way to integrate Mayan with Odoo ERP. Odoo has CMIS support, though, it has not been ported yet to version 8.0. Also, as both Mayan and Odoo are written in Python 2.7 maybe an more direct integration can be achieved. Thanks a lot for Mayan, it really enriches the Python ecosystem, even more in the enterprise category.

**Comment by rosarior** [comment]
I have zero experience with Odoo but from a few chats with people who use it, CMIS seems to hold the most promise for integration. The other way would be to build an Mayan EDMS plugin for Odoo that talk to Mayan EDMS via REST API. Thanks for that! I appreciate it!
