### ISSUE TITLE
Checkout - Checkin of document causes error

### ISSUE THREAD

**Issue by sudharsan77** [mayan-edms/mayan-edms#238]
Hi,
  When I checkout an existing document and add comments to it and try to check it in again, mayan throws up an error.

"TypeError at /checkouts/3/check/in/

view_action() takes exactly 2 arguments (1 given)"
Can someone double check on this.
Thanks

**Comment by rosarior** [comment]
For what version is this? Installed via PyPI or Git?

**Comment by sudharsan77** [comment]
Hi,
   This was for the Mayan EDMS 2.0.0b1 version which I installed via PyPI.
Do let me know if I need to get any upgrades to fix this one. Thanks

**Comment by rosarior** [comment]
Fixed with 40b94e41d811c9a380c10f7d759218f02502aac1 and added two view tests to avoid future regression. Thanks!

**Comment by rosarior** [comment]
I expect to be able to upload beta 2 sometime next week. When the release is out, upgrade doing this:

    pip install mayan-edms==2.0.0b2
    mayan-edms.py performupgrade
