### ISSUE TITLE
[v2.0]

### ISSUE THREAD

**Issue by thanhchatvn** [mayan-edms/mayan-edms#239]
Error when i deloy to ubuntu server 14
I create service nginx and mapping to mayan, everything is OK but i login page (login) , i can not attachment file to inside page. 
i chmod 777 and chown to www-data mayan foder but this is resolved this
![selection_025](https://cloud.githubusercontent.com/assets/3313064/11952124/b7c4be44-a8c8-11e5-9367-96fb5d161c62.png)
![selection_026](https://cloud.githubusercontent.com/assets/3313064/11952126/b7f2fc64-a8c8-11e5-80d1-06dc6a4d8796.png)

**Comment by rosarior** [comment]
Make sure you created the /var/log/mayan and /var/log/uwsgi directories. Stop the supervisor process, wait until all uwsgi and celery processes finish and start supervisor again. Don't user restart as it sometimes leave stale processes behind. 

This question is better suited for the mailing list: https://groups.google.com/forum/#!forum/mayan-edms

For future issues use the tracker at: https://gitlab.com/mayan-edms/mayan-edms. This issue tracker at Github is not being used or monitored anymore.

**Comment by rosarior** [comment]
https://groups.google.com/d/msg/mayan-edms/f2y87f3jwhc/2wFqeZUmCgAJ

**Comment by rosarior** [comment]
> In the file settings/production.py change the DEBUG flag from False to True. Restart supervisor with /etc/init.d/supervisor stop && sleep 30 && /etc/init.d/supervisor start and watch the console for messages. Copy and paste (or screenshot) any errors here.
