### ISSUE TITLE
$ mayan-edms.py initialsetup error

### ISSUE THREAD

**Issue by panasoft** [mayan-edms/mayan-edms#240]
Hello!
Following error appears while executing `$ mayan-edms.py initialsetup`command:
_ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory_
Possible solution is to upgrade Pillow to last version.
Could you please consider to update requirements?
Thanks!

**Comment by thequbit** [comment]
What OS are you running on?  It's possible that you do not have all of the requirements installed for pillow to work correctly.

**Comment by panasoft** [comment]
Thanks for your reply!
I use Ubuntu 14.04 LTS. Maybe there is some hidden trick with my OS configuration which is unknown for me, however other applications with Pillow dependency run just fine so far. For me the issue above was cured by upgrading Pillow to last version.

**Comment by antetna** [comment]
You are missing dependency library: 

`sudo apt-get install libjpeg62`
