### ISSUE TITLE
Where to find Mayan EDMS API Documentation ?

### ISSUE THREAD

**Issue by badhonsust** [mayan-edms/mayan-edms#244]
Can anyone suggest me to how i get all the API documentation for Mayan EDMS? 

TIA

**Comment by nirmal25990** [comment]
Did you found **Mayan EDMS API Documentation**? Please share here.

**Comment by rosarior** [comment]
Documentation is here: http://mayan.readthedocs.io/en/v2.1.7/
New manual project here (still alpha): https://gitlab.com/mayan-edms/manual
