### ISSUE TITLE
Problem while connecting from LAN

### ISSUE THREAD

**Issue by Nishant0009** [mayan-edms/mayan-edms#245]
Starting on Lubuntu server for testing.
Now its working on local server but when try to connect from within lan its not connected.

**Comment by rosarior** [comment]
By default the `runserver` command only binds to localhost.
> Note that the default IP address, 127.0.0.1, is not accessible from other machines on your network. To make your test server viewable to other machines on the network, use its own IP address (e.g. 192.168.2.1) or 0.0.0.0 or :: (with IPv6 enabled).
