### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by julianofischer** [mayan-edms/mayan-edms#247]
Hello,
can anyone answer what are the hardware requirements for using Mayan?

Thank you in advance!

**Comment by rosarior** [comment]
Hi, it can run well on small low end battery powered hardware like Odroid, Banana Pro or even Raspberry Pi, but to experience it as it was intended I would recommend a PC grade 64 bit, 1 Ghz, dual core CPU and 2 GBs of RAM as minimum. If you don't need OCR, you can get by with 1GB or RAM.

![img_20160329_011549](https://cloud.githubusercontent.com/assets/413955/22945944/60f5311c-f2cc-11e6-9bd4-b1e1f74012de.jpg)
![img_20160229_181724](https://cloud.githubusercontent.com/assets/413955/22945979/77b9e15e-f2cc-11e6-8ffc-596682f34436.jpg)

**Comment by julianofischer** [comment]
Hi @rosarior, thank you!

**Comment by rosarior** [comment]
Added to documentation in commit bcf835cd03f95a3fe2d4cdf8b430fa3ba7bab267

**Comment by julianofischer** [comment]
Awesome.
Thank you very much and congratulations.
