### ISSUE TITLE
demo displays mix of languages(english and russian)

### ISSUE THREAD

**Issue by kiswigu** [mayan-edms/mayan-edms#252]
Hi rosalio,
Please can you check the mayan edms demo, it has problem of displaying mixed of languages. Russian and english. For those who dont understand russian it becomes difficult to use demo version.

regards'
KJ

**Comment by rosarior** [comment]
Hi,

The demo is open and some users change the default language sometimes, I've
set it back to English.

Mayan EDMS can handle several languages in the user interface. The UI
translations are community contributed and some languages are not
completely translated. Mayan can do OCR for the the languages supported by
the Tesseract OCR engine, the engine Mayan EDMS uses in the backend.

**Comment by kiswigu** [comment]
hi rosalio,
Still the problem continues, can you check it again?
sorry for that.
kj

**Comment by kiswigu** [comment]
thanks it work well now
