### ISSUE TITLE
problem of adding metadata to a document

### ISSUE THREAD

**Issue by kiswigu** [mayan-edms/mayan-edms#253]
Hi! rosalio,
Please check the bug, when adding metadata to a document it displays this error:

**There's been an error. It's been reported to the site administrators via e-mail and should be fixed shortly. Thanks for your patience.**

regards.
KJ

**Comment by rosarior** [comment]
I'm unable to reproduce. Please provide more information include the document, the metadata type and the value entered.

![screenshot from 2017-06-10 17-44-12](https://user-images.githubusercontent.com/413955/27006549-98b10732-4e04-11e7-99c0-ffa293413196.png)
![screenshot from 2017-06-10 17-44-34](https://user-images.githubusercontent.com/413955/27006548-98aaeb54-4e04-11e7-81c9-bf22a6f7a427.png)

**Comment by rosarior** [comment]
Any update on this?
