### ISSUE TITLE
Add custom packages and configurations

### ISSUE THREAD

**Issue by SalahAdDin** [mayan-edms/mayan-edms#254]
I'm testing `Mayan` docker image in local, is very good.

I want to know how can we build, install, `Mayan` from source code, or if exist a way to customize and add new package to our `Mayan` setup:
Add some package for meta feautures, change the admin skin, add custom logo for the organization, etc.

I saw that the `docker` image use a local custom settings file but i'm not sure if we can use a custom `urls`  file or add new template among others.

So, can you provide a some steps for custom setup or customization procedures?

Thank you very much.

**Comment by rosarior** [comment]
Thanks for trying out Mayan.

Here is how to create your own Python packages of Mayan: http://docs.mayan-edms.com/en/v2.4/topics/development.html#installable-package

The latest Docker image includes a way to add Ubuntu packages via the MAYAN_APT_INSTALLS environments variable and Python packages via the MAYAN_PIP_INSTALLS variable.

The README for the Docker image also has instructions for creating your own images using the official image as a base: https://hub.docker.com/r/mayanedms/mayanedms/

Mayan is different from other Django apps when it comes to `urls`. The MayanAppConfig class allows apps to specify their own `urls` registrations, no need add these by hand. To add an app to a Mayan install just include the name of the app in the INSTALLED_APPS list, the rest can be controlled from the app itself.

For custom templates create a new app that overrides the /appearance/ templates path. No need or recommended to create a top level /templates folder. This is considered an anti-pattern in Mayan.

Chapter on app creation: http://docs.mayan-edms.com/en/v2.4/topics/app_creation.html

Cookie cutter template to create a skeleton Mayan app: https://gitlab.com/mayan-edms/cookiecutter-mayan

Hope these help.
