### ISSUE TITLE
Uploading a local file via api

### ISSUE THREAD

**Issue by lcerliani** [mayan-edms/mayan-edms#255]
Hi everyone,
I'm trying to upload a file via API in my Mayan (docs/#!/documents/Api_Document_List_POST). ![mayan](https://user-images.githubusercontent.com/19846607/27804258-4d010d66-6004-11e7-85bf-3634d6154d8b.PNG) But when I complete the file field with the route of my local file it doesn't let me because of the encoding. I want to know how I have to encode the file route to make this work.

Thank you very much!

Lucas.

**Comment by rosarior** [comment]
Hi,

The data type says "string" but what is required is a 'file-like object'. This can be a Python file-like object you get when using `open` or a blob object from Javascript. If using Python you can use the client library for Python: https://gitlab.com/mayan-edms/python_api_client

**Comment by rosarior** [comment]
Will leave the issue open to find a way to set the `Data Type` to something that is not confusing.

**Comment by lcerliani** [comment]
That would be good, I´m using php for using the Mayan API, so if I find a solution to create a document with php I'll post it here.

Thank you for the reply.

**Comment by rosarior** [comment]
Change committed (6b424b0eb14c56c500a443c538fac0e563bb1fed). This is how the page will look in the next version. Look forward to the PHP client code. Thanks! 

![screenshot from 2017-07-04 20-23-15](https://user-images.githubusercontent.com/413955/27844984-6c99fcc0-60f7-11e7-9a91-a322f5a6e808.png)
