### ISSUE TITLE
Make it possible to adjust values in apps\converter\literals.py from Settings

### ISSUE THREAD

**Issue by husseinlight** [mayan-edms/mayan-edms#256]
Currently the variables in apps\converter\literals.py have to be changed from the file itself - it would help to be able to adjust them, say the file format of the Preview images from the application settings. Furthermore, perhaps having the `MAYAN_` prefix for the variables in literals.py, say `MAYAN_DEFAULT_FILE_FORMAT` would be preferable than `DEFAULT_FILE_FORMAT`.

**Comment by rosarior** [comment]
Implemented in b6ffeaeb32791bb2ea041753851dda28a82230af. Thanks!
