### ISSUE TITLE
Use the DEFAULT_FILE_FORMAT from literals.py in python.py

### ISSUE THREAD

**Issue by husseinlight** [mayan-edms/mayan-edms#257]
Currently, in /apps/converter/backends/python.py, the file format passed into `pdftoppm` is being passed as a literal, as follows:

`pdftoppm = pdftoppm.bake('-jpeg')`

whereas it would be preferable to make use of the `DEFAULT_FILE_FORMAT` variable that's specified in /apps/converter/literals.py. This should be case in other parts of the application too, where the file format of preview images is being referred to.

**Comment by rosarior** [comment]
Implemented in b6ffeaeb32791bb2ea041753851dda28a82230af. Thanks!
