### ISSUE TITLE
OCR never completed

### ISSUE THREAD

**Issue by m4ntic0r** [mayan-edms/mayan-edms#260]
Today i installed Mayan EDMS on a Ubuntu 17.04 system with docker.
I uploaded three already searchable PDF files, and on all three OCR is failing and never completed.
E.g. PDF has 10 pages, OCR shows text from page 1-3, then nothing.
Next PDF has 32 pages, OCR shows text from page 1-6, then nothing.

There are no OCR Errors listed in the system tools.

Its really not useable with such bugs.. the pdfs are already searchable and after upload i can not search these documents because a huge part is not done with ocr?

**Comment by m4nticOr** [comment]
I opened this issue 14 hours ago and still no answer!

What gives?
