### ISSUE TITLE
fix_orientation method causes document add to crash

### ISSUE THREAD

**Issue by Chluz** [mayan-edms/mayan-edms#261]
Hi, 

just started trying out Mayan and got some crashes on pdfs scanned by a printer.
The error was as follows 
```
[2017-07-29 22:41:44,211: ERROR/Worker-4] Error creating new document version for document "BuchungsbestaetigungDuppa055.pdf"; unsupported operand type(s) for -: 'int' and 'IndirectObject'
sources.models <125> [CRITICAL] "upload_document() line 127 Unexpected exception while trying to create version for new document "BuchungsbestaetigungDuppa055.pdf" from source "Default Watch Folder"; unsupported operand type(s) for -: 'int' and 'IndirectObject'"
[2017-07-29 22:41:44,211: CRITICAL/Worker-4] Unexpected exception while trying to create version for new document "BuchungsbestaetigungDuppa055.pdf" from source "Default Watch Folder"; unsupported operand type(s) for -: 'int' and 'IndirectObject'
sources.tasks <125> [ERROR] "task_check_interval_source() line 30 Error processing source: Default Watch Folder; unsupported operand type(s) for -: 'int' and 'IndirectObject'"
[2017-07-29 22:41:44,307: ERROR/Worker-4] Error processing source: Default Watch Folder; unsupported operand type(s) for -: 'int' and 'IndirectObject'
```
I then attempted importing the dame document through the webform and got a similar error. 

I tracked the error to the fix_orientation method. After commenting out line 435 in /usr/local/lib/python2.7/dist-packages/mayan/apps/documents/models.py the imports work fine. 

Any idea what is happening ?

Thanks for your help

**Comment by rosarior** [comment]
Thanks @Chluz for the report and the information, seems to be a typecasting issue. Working on ti.

**Comment by rosarior** [comment]
Seems it is an issue with the way the PDF is being generated. Found instances for this error in other software: https://github.com/mstamy2/PyPDF2/pull/338

Can you provide a blank PDF that triggers the issue to create a test and a workaround?

Thanks.

**Comment by Chluz** [comment]
Will this do ? Its triggering the error on a webform import, but its not blank.
[](https://cloud.luzzato.com/index.php/s/ZgNwzePp9rYzsOB )

Password London123=

**Comment by rosarior** [comment]
Tried it and it triggers the error on my build too. Can confirm that the change in 28b4c9a5460ffc7a430d12731d9c0f7a9173373f fixes it. Thank you!

I asked for a blank page PDF to be able to add it permanently as a test document for the unit tests (https://github.com/mayan-edms/mayan-edms/tree/master/mayan/apps/documents/tests/contrib/sample_documents) to avoid a future regression. But if it's not possible its ok too. 

Thanks for the report and the information to pinpoint it.

**Comment by Chluz** [comment]
Hi Rosarior, I understand, here is a blank PDF that causes the same issue on the unpatched version
[file](https://cloud.luzzato.com/index.php/s/s9cYsFsQb8jX10L)

**Comment by rosarior** [comment]
Added via 7a67604551a8410a2579ecebab67b0c7e51f32e0. Thanks!
