### ISSUE TITLE
Error processing source: unsupported operand type(s) for -: 'int' and 'IndirectObject'

### ISSUE THREAD

**Issue by PenDragon78** [mayan-edms/mayan-edms#266]
Watched folders don't seem to be working, throws a:

Error processing source: unsupported operand type(s) for -: 'int' and 'IndirectObject'
--

and doesn't process documents in the directory.

**Comment by rosarior** [comment]
Do you have PDF files int he watch folder? Try removing all files and using just a JPG or PNG file to see if it is a manifestation of error #261 (https://github.com/mayan-edms/mayan-edms/issues/261).

**Comment by PenDragon78** [comment]
Looks like that's likely the issue. JPG and PDF's not from my scanner seem to work fine. Using the docker image, so will try and figure out how to update with the patch and then test. Thanks!

**Comment by rosarior** [comment]
Version 2.7 has been releases with a fix for this. Thanks for reporting.
