### ISSUE TITLE
Fail to install ImportError: No module named django.utils

### ISSUE THREAD

**Issue by nenad007** [mayan-edms/mayan-edms#268]
pip install mayan-edms fails on:

    Downloading/unpacking django-colorful==1.2 (from mayan-edms)
      Downloading django-colorful-1.2.tar.gz
      Running setup.py egg_info for package django-colorful
        Traceback (most recent call last):
          File "<string>", line 16, in <module>
          File "/usr/share/mayan-edms/build/django-colorful/setup.py", line 4, in <module>
            import colorful
          File "colorful/__init__.py", line 3, in <module>
            from django.utils import version
        ImportError: No module named django.utils
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/usr/share/mayan-edms/build/django-colorful/setup.py", line 4, in <module>

        import colorful

      File "colorful/__init__.py", line 3, in <module>

        from django.utils import version

    ImportError: No module named django.utils

    ----------------------------------------
    Cleaning up...

Exist there any workaround?

**Comment by rosarior** [comment]
For which version is this?
Are you using virtualenv?

**Comment by nenad007** [comment]
Pip download mayan-edms 2.7.3 and yes I used virtualenv and followed:

    virtualenv mayan-edms
    source mayan-edms/bin/activate
    pip install mayan-edms

**Comment by rosarior** [comment]
Try a previous version to see if the issue is with the packaging or the environment:
    
    pip install mayan-edms==2.6.4

and:

   pip install mayan-edms==2.5.2

**Comment by nenad007** [comment]
I have tried 2.6.4, 2.5.2, 2.4 and 2.2 all failed on the same step.

    python -V
    Python 2.7.5

Do you have any idea what I could try more?

**Comment by nenad007** [comment]
I found a solution to install latest mayan on a plain Centos 7 with latest updates:

    pip install mayan-edms==2.0
    pip install --upgrade setuptools  --> needed, without update fails
    pip install -U mayan-edms

This in case someone has the same Issue as me.
