### ISSUE TITLE
Next release questions

### ISSUE THREAD

**Issue by juanfcocontreras** [mayan-edms/mayan-edms#274]
I'm planning to install mayan-edms, but I've seen in next-version branch that a new 3.0 version is on the way. Is there any estimation when it is going to be available?

Also, 2.7 version was supposed to be the latest version with the current OCR. Is it still valid or 3.0 includes the same previous versions OCR engine?

Thanks!

**Comment by Im-PJ** [comment]
There is no news after this happened. https://www.mayan-edms.com/post/hurricane-maria/
Would love to hear from @rosarior Hope he is doing well.

**Comment by rosarior** [comment]
Hi, 

Yes, development has restarted and we are close to a 3.0 release. The OCR functionality will stay in the code.

The hurricanes did a good number on the infrastructure of the island. The constant blackouts and telecom outages are what's slowing down the new releases of Mayan and my other FOSS projects. I've built a simple solar power system to be able to work and keep a few single board computers as servers using this rig. This system is simple and needs to be upgraded and increased in capacity and runtime. Donations to Mayan EDMS are going directly into improving this system. Donation link is below the header in the main page at: https://www.mayan-edms.com/

Thanks.
