### ISSUE TITLE
Documents thumbnail are not retrieved while dockerizing the application.

### ISSUE THREAD

**Issue by kamranrafi123** [mayan-edms/mayan-edms#276]
On dockerizing the application documents thumbnail does not retrieve, instead it shows cross sign.

**Comment by eriggs** [comment]
A bug report without debug info is not much help. Here is how to open the Javascript console in different browsers => https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers

Add any error message here.
