### ISSUE TITLE
Out of Memory exception when converting Office documents

### ISSUE THREAD

**Issue by dpavlic** [mayan-edms/mayan-edms#53]
This is a bug that I am having some difficulty with tracking on my CentOS server. I have enabled the previews, and after a few uploads of Office documents, I get a Out of Memory exception, with the traceback in Debug mode showing a problem to be in subprocess:

OSError at /sources/upload/document/100/version/interactive/
[Errno 12] Cannot allocate memory
Request Method:  POST
Request URL:  http://127.0.0.1:8090/sources/upload/document/100/version/interactive/
Django Version:  1.6.5
Exception Type:  OSError
Exception Value:  
[Errno 12] Cannot allocate memory
Exception Location:  /usr/lib64/python2.6/subprocess.py in _execute_child, line 1144
Python Executable:  /envmayan/bin/python
Python Version:  2.6.6
...

If Debug mode is off, a red rectagnle shows up on top of the screen with the error "[Errno 12] Cannot allocate memory".

I have deployed mayan with gunicorn and if I restart it once I get this message, all works as expected. But as soon as I begin to upload documents, it's not too long before I'm out of memory again, at which point the only solution is another gunicorn restart. 

Opening up live previews or doing anything of that sort seems to massively increase the amount of memory of a gunicorn worker, so my guess is that the preview images are stored in memory (although I can't really find the relevant code for this). If that is correct, the image memory cache seems to only be freed up when it gets very close to the memory user limit since it never really goes down before the limit is hit (memory usage seems to reset for a gunicorn worker when memory usage gets close to the user limit). Is it possible that since django is calling an external process, libreoffice, to do the conversion, that there is genuinely not enough memory since the cache is not cleared beforehand?

**Comment by rosarior** [comment]
Can you please test again with the latest development version to see if the problem persists? Thanks!

**Comment by dpavlic** [comment]
Hi Rosario,

Sorry for the radio silence.

We have the EDMS deployed, so I can't test it on the production system. I'll see if I can clone the database and set up a test virtual machine this weekend on the latest development version.

**Comment by rosarior** [comment]
Good to hear! There is now a Vagrant file to make it easier to setup a development server for when you get a change. Thanks!

**Comment by dpavlic** [comment]
Sorry for taking longer on this.  I did some testing yesterday and cannot reproduce the error, but I didn't do a database clone as the contents are *somewhat* sensitive and mock deployment could only be done on my work server...  In any case, with this limited test (a few heavy Word documents and some PDFs), I could not reproduce the earlier error.

**Comment by rosarior** [comment]
No worries, thanks for testing, re-open if you encounter the issue again. Thanks!
