### ISSUE TITLE
Feature:  possibility to update/choose metadata directly on the upload form

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#9]
Currently the actual metadata for a new document are displayed on the side of the upload form. It would be nice to be able to change those metadata directly instead of having to go to the upload workflow from the beginning.

I imagine some kind of split form, where on one side it is possible to choose the metadata, on the other side the upload for as currently is.

**Comment by rosarior** [comment]
Deferring to post 1.1 release and after merging @EmlynC bootstrap pull request (#121) to avoid modernizing the wizard templates that will be discarded anyways for the merge.
